[package]
name = "cargo-release"
version = "0.1.0"
authors = ["Ning Sun <sunng@about.me>"]
license = "MIT/Apache-2.0"
description = "cargo release command"

[dependencies]
toml = "0.1.27"
semver = "0.2.3"
quick-error = "0.1.3"
regex = "0.1.55"
