[package]
name = "cargo-release"
version = "0.2.1"
authors = ["Ning Sun <sunng@about.me>"]
license = "MIT/Apache-2.0"
description = "cargo release command"
keywords = ["cargo"]
repository = "https://github.com/sunng87/cargo-release"

[dependencies]
toml = {version = "0.1.27", default-features = false}
semver = "0.2.3"
quick-error = "0.1.3"
regex = "0.1.55"
clap = "2.1.2"
