[package]
name = "cargo-release"
version = "0.8.1-pre"
authors = ["Ning Sun <sunng@about.me>"]
license = "MIT/Apache-2.0"
description = "cargo release command"
keywords = ["cargo"]
repository = "https://github.com/sunng87/cargo-release"

[dependencies]
toml = {version = "0.3.1", default-features = false}
semver = "0.6.0"
quick-error = "1.1.0"
regex = "0.2.1"
clap = "2.22.1"
ansi_term = "0.9.0"
maplit = "0.1.4"

[badges]
travis-ci = { repository = "sunng87/cargo-release", branch="0.8.0" }

[package.metadata.release]
sign-commit = true
#upload-doc = true
pre-release-hook = "./hook.sh"
pre-release-replacements = [ {file="README.md", search="Current release: [a-z0-9\\.-]+", replace="Current release: {{version}}"} , {file ="Cargo.toml", search="branch=\"[a-z0-9\\.-]+\"", replace="branch=\"{{version}}\""} ]
