[package]
name = "cargo-release"
version = "0.10.1-alpha.0"
authors = ["Ning Sun <sunng@about.me>"]
license = "MIT/Apache-2.0"
description = "cargo release command"
keywords = ["cargo"]
categories = ["development-tools::cargo-plugins"]
repository = "https://github.com/sunng87/cargo-release"

[dependencies]
toml = {version = "0.3.1", default-features = false}
semver = "0.6.0"
quick-error = "1.1.0"
regex = "0.2.1"
clap = "2.22.1"
ansi_term = "0.9.0"
maplit = "0.1.4"
chrono = "0.4"

[badges]
travis-ci = { repository = "sunng87/cargo-release", branch="0.10.0" }
